server:
  port: 8081
spring:
  application:
    name: shades
logging:
  level:
    ROOT: DEBUG

downstream:
  soma:
    # connectIp: http://192.168.1.30:3000
    connectIp: http://192.168.1.13:3000 # intentional bad IP address
    # connectIp: http://localhost:8083
  sunsa:
    baseUrl: https://sunsahomes.com/api/public
    apiKey: 6048c8b7-5d39-4a60-ae5f-73da348d6c8b
    idUser: "4963"
  retries: 2
  api:
    soma:
      listDevices:
        path: /list_devices
      openShade:
        path: /open_shade/{id}
      closeShade:
        path: /close_shade/{id}
      closeAllShades:
        path: /close_all_shades
      setShadePosition:
        path: /set_shade_position/{id}/{position}
      stopShade:
        path: /stop_shade/{id}
      getShadeState:
        path: /get_shade_state/{id}
      getLightLevel:
        path: /get_light_level/{id}
      getBatteryLevel:
        path: /get_battery_level/{id}
    sunsa:
      listDevices:
        path: /{idUser}/devices
      setShadePosition:
        path: /api/public/{idUser}/devices/{idDevice}
  devices:
    - id: "d8:85:46:5b:0c:55"
      type: soma
      name: OfficeLeft
      seasonalDefault: 35
      groups: ["Office", "Seasonal", "All"]
    - id: "de:75:b8:79:20:4c"
      type: soma
      name: OfficeMiddle
      seasonalDefault: 35
      groups: ["Office", "Seasonal", "All"]
    - id: "de:b8:32:e4:63:21"
      type: soma
      name: OfficeRight
      seasonalDefault: 35
      groups: ["Office", "Seasonal", "All"]
    - id: "c6:08:10:c8:f7:64"
      type: soma
      name: KitchenRear
      seasonalDefault: 0
      groups: ["Kitchen", "All"]
    - id: "d0:e4:4e:28:c5:ae"
      type: soma
      name: KitchenSide
      seasonalDefault: 25
      groups: ["Kitchen", "Seasonal", "All"]
    - id: "dc:e4:75:97:b0:60"
      type: soma
      name: LivingLeft
      seasonalDefault: 0
      groups: ["Living", "All"]
    - id: "cd:1e:bd:f5:9b:af"
      type: soma
      name: LivingMiddle
      seasonalDefault: 0
      groups: ["Living", "All"]
    - id: "fd:a1:05:1a:e8:d6"
      type: soma
      name: LivingRight
      seasonalDefault: 0
      groups: ["Living", "All"]
    - id: "16600"
      type: sunsa
      name: MikiOffice
      seasonalDefault: 0
      groups: ["All"]



#  macMap.put("c6:08:10:c8:f7:64", "KitchenRear");
#  macMap.put("d0:e4:4e:28:c5:ae", "KitchenSide");
#  macMap.put("dc:e4:75:97:b0:60", "LivingLeft");
#  macMap.put("cd:1e:bd:f5:9b:af", "LivingMiddle");
#  macMap.put("fd:a1:05:1a:e8:d6", "LivingRight");
#  macMap.put("d8:85:46:5b:0c:55", "OfficeLeft");
#  macMap.put("de:75:b8:79:20:4c", "OfficeMiddle");
#  macMap.put("de:b8:32:e4:63:21", "OfficeRight");
